export const categories = [
    { id: 1, value: "icons", label: "Icons" },
    { id: 2, value: "amazing_views", label: "Amazing Views" },
    { id: 3, value: "farms", label: "Farms" },
    { id: 4, value: "amazing_pools", label: "Amazing Pools" },
    { id: 5, value: "top_cities", label: "Top Cities" },
    { id: 6, value: "castles", label: "Castles" },
    { id: 7, value: "beachfront", label: "Beachfront" },
    { id: 8, value: "omg", label: "OMG!" },
    { id: 9, value: "countryside", label: "Countryside" },
    { id: 10, value: "rooms", label: "Rooms" },
    { id: 11, value: "lakefront", label: "Lakefront" },
    { id: 12, value: "cabins", label: "Cabins" },
    { id: 13, value: "islands", label: "Islands" },
    { id: 14, value: "mansions", label: "Mansions" },
    { id: 15, value: "historical_homes", label: "Historical Homes" },
    { id: 16, value: "techhouses", label: "Techhouses" },
    { id: 17, value: "luxe", label: "Luxe" },
    { id: 18, value: "tiny_homes", label: "Tiny Homes" },
    { id: 19, value: "bed_breakfasts", label: "Bed & Breakfasts" },
    { id: 20, value: "national_parks", label: "National Parks" },
    { id: 21, value: "house_boats", label: "House Boats" },
    { id: 22, value: "top_of_the_world", label: "Top of the World" }
  ];
  
